global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'web'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ['web:8080']

  - job_name: 'web-node_exporter'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['web:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'  # Alertmanager의 주소

rule_files:
  - '/etc/prometheus/alert_rules.yml'  # 알림 규칙 파일